version: "3.8"
services:
  test-app:
    build:
      args:
        user: efx
        uid: 1000
      context: ./api
      dockerfile: Dockerfile
    image: cus-app-test-img
    container_name: cus-test-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api:/var/www
    networks:
      - development
networks:
  development:
    driver: bridge